version: "3"

tasks:
  default:
    cmds:
      - task -l
    silent: true

  build:
    desc: Build using version number from .env
    cmds:
      - docker compose -f build/docker-compose.yml build app

  build:devcontainer-base-local:
    desc: Build local base image for devcontainer without pulling from registry
    cmds:
      - docker build -f build/Dockerfile.debian -t devcontainer.debian.polyhost:local build

  push:
    desc: Push image to registry (requires DOCKER_REGISTRY, REPO_NAME, IMAGE_TAG in .env)
    deps:
      - build
    cmds:
      - build/push-with-retry.sh

  build-and-push:
    desc: Build image with version and push to registry
    cmds:
      - task build
      - task push
