#!/usr/bin/env bash
# Regenerates .devcontainer/debian/.env from build/.env so the registry/tag
# used by the devcontainer base image never drifts out of sync with the
# values used to build/push that image.
set -euo pipefail

dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd -- "$dir/../.." && pwd)"
build_env="$repo_root/build/.env"
out_env="$repo_root/.devcontainer/debian/.env"

if [[ ! -f "$build_env" ]]; then
  echo "ERROR: $build_env not found" >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$build_env"
set +a

: "${IMAGE_NAMESPACE:?IMAGE_NAMESPACE not set in build/.env}"
: "${IMAGE_NAME:?IMAGE_NAME not set in build/.env}"
: "${IMAGE_TAG:?IMAGE_TAG not set in build/.env}"

cat > "$out_env" <<EOF
# Generated by .devcontainer/scripts/sync-build-env.sh from build/.env.
# Do not edit by hand — edit build/.env and re-run the script instead.
DEVCONTAINER_BASE_IMAGE=${IMAGE_NAMESPACE}/${IMAGE_NAME}
IMAGE_TAG=${IMAGE_TAG}
EOF

echo "Synced $out_env from build/.env"
